

export const products = [
    {
      id: 1,
      nombre: "Taladro Inalámbrico 20V",
      descripcion: "Taladro potente con batería de larga duración para todo tipo de trabajos.",
      precio: 69990,
      categoria: "Herramientas eléctricas",
      imagen: "/images/taladro1.jpg",
    },
    {
      id: 2,
      nombre: "Martillo de Carpintero",
      descripcion: "Martillo de acero con mango ergonómico para trabajos de precisión.",
      precio: 12990,
      categoria: "Herramientas manuales",
      imagen: "/images/martillocarp.jpg",
    },
    {
      id: 3,
      nombre: "Set de Llaves Allen",
      descripcion: "Juego completo de llaves en medidas métricas y estándar.",
      precio: 8990,
      categoria: "Herramientas manuales",
      imagen: "/images/allen.webp",
    },
    {
      id: 4,
      nombre: "Sierra Circular 7 1/4''",
      descripcion: "Corta madera y materiales compuestos con precisión.",
      precio: 84990,
      categoria: "Herramientas eléctricas",
      imagen: "/images/sierra.webp",
    },
    {
      id: 5,
      nombre: "Juego de Brocas para Metal",
      descripcion: "Brocas de alta resistencia para perforaciones en acero.",
      precio: 15990,
      categoria: "Accesorios",
      imagen: "/images/brocas.jpg",
    },
    {
      id: 6,
      nombre: "Caja de Herramientas 50 piezas",
      descripcion: "Incluye martillo, llaves, destornilladores y más.",
      precio: 49990,
      categoria: "Herramientas manuales",
      imagen: "/images/set.webp",
    },
    {
      id: 7,
      nombre: "Amoladora Angular 4 1/2''",
      descripcion: "Para corte y desbaste de metal y piedra.",
      precio: 42990,
      categoria: "Herramientas eléctricas",
      imagen: "/images/amoladora.jpg",
    },
    {
      id: 8,
      nombre: "Cinta Métrica 5m",
      descripcion: "Cuerpo reforzado, cinta de acero de alta resistencia.",
      precio: 3990,
      categoria: "Medición",
      imagen: "/images/cintametrica.jpeg",
    },
    {
      id: 9,
      nombre: "Nivel de Burbuja Profesional",
      descripcion: "Para mediciones precisas en obra y carpintería.",
      precio: 8990,
      categoria: "Medición",
      imagen: "/images/nivel.webp",
    },
    {
      id: 10,
      nombre: "Cortadora de Baldosas Manual",
      descripcion: "Ideal para cortes limpios y precisos en cerámica.",
      precio: 64990,
      categoria: "Herramientas manuales",
      imagen: "/images/cortacera.webp",
    },
    {
      id: 11,
      nombre: "Pistola de Silicona 60W",
      descripcion: "Perfecta para proyectos de bricolaje y manualidades.",
      precio: 7990,
      categoria: "Accesorios",
      imagen: "/images/pistola.jpeg",
    },
    {
      id: 12,
      nombre: "Destornillador Inalámbrico",
      descripcion: "Compacto y liviano, ideal para el hogar.",
      precio: 27990,
      categoria: "Herramientas eléctricas",
      imagen: "/images/destornillador.jpg",
    },
    {
      id: 13,
      nombre: "Llave Ajustable 10''",
      descripcion: "Perfecta para plomería y ajustes en general.",
      precio: 11990,
      categoria: "Herramientas manuales",
      imagen: "/images/francesa.jpg",
    },
    {
      id: 14,
      nombre: "Cutter Profesional",
      descripcion: "Cuerpo metálico, cuchillas intercambiables.",
      precio: 2990,
      categoria: "Accesorios",
      imagen: "/images/cutter.jpg",
    },
    {
      id: 15,
      nombre: "Set de Brochas para Pintar",
      descripcion: "Variedad de tamaños para proyectos de pintura.",
      precio: 4990,
      categoria: "Pintura",
      imagen: "/images/brochas.webp",
    },
    {
      id: 16,
      nombre: "Guantes de Seguridad",
      descripcion: "Protección contra cortes y abrasiones.",
      precio: 3990,
      categoria: "Seguridad",
      imagen: "/images/guantes.webp",
    },
    {
      id: 17,
      nombre: "Escalera Aluminio 6 peldaños",
      descripcion: "Ligera, resistente y segura para trabajos en altura.",
      precio: 59990,
      categoria: "Accesorios",
      imagen: "/images/escalera.avif",
    },
    {
      id: 18,
      nombre: "Disco de Corte Metal 4 1/2''",
      descripcion: "Disco de alta velocidad para cortes limpios.",
      precio: 1990,
      categoria: "Accesorios",
      imagen: "/images/discocorte.avif",
    },
    {
      id: 19,
      nombre: "Pistola de Pintura HVLP",
      descripcion: "Acabados profesionales en pinturas de alta precisión.",
      precio: 34990,
      categoria: "Pintura",
      imagen: "/images/pistolapintura.webp",
    },
    {
      id: 20,
      nombre: "Multímetro Digital",
      descripcion: "Para medir voltajes, resistencia y corriente.",
      precio: 15990,
      categoria: "Medición",
      imagen: "/images/multimetro.jpg",
    },
    {
      id: 21,
      nombre: "Cerradura de Seguridad",
      descripcion: "Protección adicional para puertas principales.",
      precio: 22990,
      categoria: "Seguridad",
      imagen: "/images/cerradura.webp",
    },
    {
      id: 22,
      nombre: "Manguera de Jardín 20m",
      descripcion: "Flexible, resistente a torceduras y presión.",
      precio: 18990,
      categoria: "Jardinería",
      imagen: "/images/manguera.webp",
    },
    {
      id: 23,
      nombre: "Cizalla para Cortar Metal",
      descripcion: "Ideal para láminas delgadas de acero o aluminio.",
      precio: 25990,
      categoria: "Herramientas manuales",
      imagen: "/images/cizalla.webp",
    },
    {
      id: 24,
      nombre: "Mascarilla de Protección N95",
      descripcion: "Protección respiratoria en ambientes polvorientos.",
      precio: 2990,
      categoria: "Seguridad",
      imagen: "/images/mascarilla.webp",
    },
    {
      id: 25,
      nombre: "Cinta de Teflón",
      descripcion: "Sellado hermético para uniones roscadas.",
      precio: 990,
      categoria: "Accesorios",
      imagen: "/images/cintateflon.jpg",
    },


  {
    id: 26,
    nombre: "Cortadora de Césped Eléctrica",
    descripcion: "Compacta y potente, ideal para jardines medianos.",
    precio: 99990,
    categoria: "Jardinería",
    imagen: "/images/cortadora.webp",
  },
  {
    id: 27,
    nombre: "Sierra Caladora",
    descripcion: "Corte rápido y preciso en madera y plástico.",
    precio: 45990,
    categoria: "Herramientas eléctricas",
    imagen: "/images/caladora.webp",
  },
  {
    id: 28,
    nombre: "Extensión Eléctrica 10m",
    descripcion: "Cable reforzado ideal para exteriores e interiores.",
    precio: 7990,
    categoria: "Accesorios",
    imagen: "/images/cable.webp",
  },
  {
    id: 29,
    nombre: "Taladro Percutor 800W",
    descripcion: "Para perforaciones en concreto, madera y metal.",
    precio: 54990,
    categoria: "Herramientas eléctricas",
    imagen: "/images/percutor.webp",
  },
  {
    id: 30,
    nombre: "Barreta de Acero 5 pies",
    descripcion: "Herramienta esencial para demolición pesada.",
    precio: 18990,
    categoria: "Herramientas manuales",
    imagen: "/images/barreta.jpg",
  },
  {
    id: 31,
    nombre: "Atornillador de Impacto",
    descripcion: "Ideal para construcción y montaje de estructuras.",
    precio: 66990,
    categoria: "Herramientas eléctricas",
    imagen: "/images/impacto.webp",
  },
  {
    id: 32,
    nombre: "Carretilla de Obra",
    descripcion: "Capacidad de 90 litros, acero reforzado.",
    precio: 39990,
    categoria: "Construcción",
    imagen: "/images/carretilla.png",
  },
  {
    id: 33,
    nombre: "Compresor de Aire 50L",
    descripcion: "Potente para herramientas neumáticas.",
    precio: 229990,
    categoria: "Herramientas eléctricas",
    imagen: "/images/compresor.jpg",
  },
  {
    id: 34,
    nombre: "Motosierra a Gasolina",
    descripcion: "Ideal para corte de árboles y poda pesada.",
    precio: 189990,
    categoria: "Jardinería",
    imagen: "/images/motosierra.webp",
  },
  {
    id: 35,
    nombre: "Juego de Destornilladores 12 piezas",
    descripcion: "Variedad de puntas planas y philips.",
    precio: 14990,
    categoria: "Herramientas manuales",
    imagen: "/images/destornilladores.jpeg",
  },
  {
    id: 36,
    nombre: "Esmeriladora de Banco",
    descripcion: "Afilado de herramientas y piezas metálicas.",
    precio: 84990,
    categoria: "Herramientas eléctricas",
    imagen: "/images/esmerildebanco.webp",
  },
  {
    id: 37,
    nombre: "Manguera de Alta Presión",
    descripcion: "Compatible con hidrolavadoras de agua.",
    precio: 34990,
    categoria: "Jardinería",
    imagen: "/images/mangueradepresion.webp",
  },
  {
    id: 38,
    nombre: "Set de Llaves Combinadas",
    descripcion: "Incluye 12 tamaños diferentes en acero al cromo.",
    precio: 25990,
    categoria: "Herramientas manuales",
    imagen: "/images/llaves.avif",
  },
  {
    id: 39,
    nombre: "Soldadora Inverter 200A",
    descripcion: "Soldaduras de alta precisión y bajo consumo.",
    precio: 159990,
    categoria: "Construcción",
    imagen: "/images/soldadora.jpg",
  },
  {
    id: 40,
    nombre: "Rodillo de Pintura Antigoteo",
    descripcion: "Para un acabado perfecto y sin manchas.",
    precio: 6990,
    categoria: "Pintura",
    imagen: "/images/rodillo.webp",
  },
  {
    id: 41,
    nombre: "Sopladora de Hojas Eléctrica",
    descripcion: "Mantén el jardín limpio en minutos.",
    precio: 69990,
    categoria: "Jardinería",
    imagen: "/images/sopladora.png",
  },
  {
    id: 42,
    nombre: "Caja Organizadora de Tornillos",
    descripcion: "Separadores ajustables para máxima organización.",
    precio: 9990,
    categoria: "Accesorios",
    imagen: "/images/caja.avif",
  },
  {
    id: 43,
    nombre: "Linterna Led Recargable",
    descripcion: "Alta duración y alcance de hasta 300 metros.",
    precio: 19990,
    categoria: "Accesorios",
    imagen: "/images/linterna.jpg",
  },
  {
    id: 44,
    nombre: "Pinza de Presión 10''",
    descripcion: "Sujeción firme para trabajos de soldadura o ajuste.",
    precio: 11990,
    categoria: "Herramientas manuales",
    imagen: "/images/caiman.webp",
  },
  {
    id: 45,
    nombre: "Masilla para Madera",
    descripcion: "Ideal para reparar imperfecciones antes de pintar.",
    precio: 5990,
    categoria: "Pintura",
    imagen: "/images/masilla.jpeg",
  },
  {
    id: 46,
    nombre: "Disco Diamantado para Cerámica",
    descripcion: "Corte limpio en baldosas y porcelanato.",
    precio: 10990,
    categoria: "Accesorios",
    imagen: "/images/diamantado.jpg",
  },
  {
    id: 47,
    nombre: "Andamio Plegable de Acero",
    descripcion: "Trabajos seguros en alturas medias.",
    precio: 159990,
    categoria: "Construcción",
    imagen: "/images/andamio.jpg",
  },
  {
    id: 48,
    nombre: "Espátula Flexible de Acero",
    descripcion: "Ideal para aplicar masillas o raspar pintura vieja.",
    precio: 3990,
    categoria: "Pintura",
    imagen: "/images/espatula.webp",
  },
  {
    id: 49,
    nombre: "Broca para Concreto 6mm",
    descripcion: "Ideal para perforaciones en concreto y ladrillo.",
    precio: 1490,
    categoria: "Accesorios",
    imagen: "/images/broca6.webp",
  },
  {
    id: 50,
    nombre: "Pala de Punta Acero",
    descripcion: "Resistente, ideal para excavaciones pesadas.",
    precio: 17990,
    categoria: "Construcción",
    imagen: "/images/pala.jpg",
  }
];
